### ISSUE TITLE
Need help with setup deployment of whl files for windows and mac to pypi.org

### ISSUE THREAD

**Issue by insolor** [pymorphy2-fork/DAWG#4]

**Comment by bt2901** [comment]
I have some experience with `cibuildwheel` package (see https://github.com/bt2901/bigartm/blob/setup_discuss/.travis.yml), but my available time is very limited currently. I might try helping at some moment in the future, provided it is still needed.

**Comment by insolor** [comment]
It's ok, this is not a high priority task. If you can help with this, it would be very much appreciated.

**Comment by bt2901** [comment]
this also looks highly relevant: https://github.com/pypa/cibuildwheel/issues/404

Look how `setup.py` deals with Cython extensions: https://github.com/IBM/sib/blob/master/setup.py#L56

I'll experiment with that on my fork (https://github.com/bt2901/DAWG/tree/cibw), for now I don't quite understand how it works.

**Comment by bt2901** [comment]
https://github.com/bt2901/DAWG/actions/runs/5896294553#artifacts

I think it works? The Linux job took over 6 hours and timed out for some reason (it appears that something went wrong in the very last step, `exec /usr/local/bin/manylinux-entrypoint: exec format error` was frozen for 5:53), but you can download wheels for Win and MacOS.

**Comment by insolor** [comment]
@bt2901, good, I'll check this out later

**Comment by bt2901** [comment]
might be relevant: https://github.com/pypa/cibuildwheel/issues/1189 

or alternatively I could try disabling some of the architectures

**Comment by insolor** [comment]
In the worst case, we can simply not bundle wheels for Linux. It's a rare case where there are some problems with building from source on Linux.

**Comment by insolor** [comment]
P.S. however, no, it need at least python3-dev package to be installed on my computer (not to mention the build tools). So having ready wheels for Linux would be nice too.

As for architectures, I'm not sure if we need ARM64 for Windows, also I think we can already drop Python 3.6, and not build yet for Python 3.12.

**Comment by bt2901** [comment]
Removing the `aarch64` did the trick. `aarch64` is an emulated architecture (see https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation for an example of how it could be done), and it seems to be more trouble that it's worth, since I doubt anybody is going to build dictionaries using Raspberry Pi ;) (and if needed, `aarch64` users should still be able to use pure python implementation of DAWG).
